### ISSUE TITLE
Pretrained weights on those datasets

### ISSUE THREAD

**Issue by xwan6266** [LouieShao/1st-Place-Solution-in-Google-Universal-Image-Embedding#1]
Dear  Author,
It's amazing to see that you achieved 1st place. 
Thanks for your nice work and detailed explanation about the method.
Just want to ask, is there a plan to release the model weights trained on those datasets?
Cheers,
Gavin

**Comment by LouieShao** [comment]
Thank you! Since recently I've got a busy schedule, the weights will be released about 1~2 weeks later, and once it got released i will mention in this thread to let you know as well!

**Comment by xwan6266** [comment]
I got it.
Thanks a lot for your response!

Best Regards,
Gavin

LouieShao ***@***.***> 于2023年3月2日周四 13:54写道：

**Comment by ShihaoShao-GH** [comment]
The weights are availiable now. Closing this issue.
